### ISSUE TITLE
When I wanted to train, I had a new problem.

### ISSUE THREAD

**Issue by pandaxue** [metal3d/keras-video-generators#2]
sorry , When I wanted to train, I had a new problem.
'ValueError: 'C:/Users/babyblue/Desktop/deeplearning/videos/kick_ball' is not in list'
![image](https://user-images.githubusercontent.com/50400428/70139967-a8d7a400-16ce-11ea-8148-4aa97b77d381.png)

**Comment by metal3d** [comment]
OK, Windows user should have problems, I will update that to fix the path sep (it seems that the problem is that one)

**Comment by metal3d** [comment]
https://github.com/metal3d/keras-video-generators/blob/master/src/keras_video/generator.py#L185 weird, I did it... it seems that `os.sep` is the problem. And as I don't have any Windows to fix...

It's clear that instead of getting the class name, it stores the full path...

The question is... why ? ...

Can you give me the result of:

```python
import os
print(os.sep)
print(os.path.sep)
```

**Comment by pandaxue** [comment]
![image](https://user-images.githubusercontent.com/50400428/70329284-08bc7f00-1876-11ea-94f4-cd946a9b354f.png)

**Comment by Benan-Akca** [comment]
I think the problem is because of the difference in path styles between windows and Linux
            video = self.files[i]
            classname = video.split(os.sep)[-2]
In that part of code, video path had format like "videos\dribble" but as my knowledge in windows, split(os.sep) function doesn't work with one separator (\) it needs two separators to indicate that the entries are not special characters starting with \ or you can use “r” as a prefix to indicate that special characters should not be evaluated.
As like r"videos\dribble"

**Comment by Benan-Akca** [comment]
I changed two lines of code below to solve the format issue
```
classes = [i.split(os.path.sep)[1] for i in glob.glob('videos\*')] #  "\"  changed here
...
glob_pattern=r'videos\{classname}\*.avi' 
```
Then it throws  **_'ProgbarLogger' object has no attribute 'log_values'_** error

After a search on the internet for that error, I found that when we set **_verbose = 0 in model.fit_generator( verbose=0)_**  code works successfully.

**Comment by metal3d** [comment]
Yes, that's why I'm using `os.path.sep` in the package, the problem can appear if you're using example from the medium article. I will fix the article to help.

So, is it working now? (To close that issue)

**Comment by sintaba** [comment]
It's working great. 
Thank you very much.

**Comment by metal3d** [comment]
Happy that it works for you :+1: Don't hesitate if you've got other problems.
